Stop Postgres wanting a password in docker-compose
On running `docker-compose up`, I got the following error from the Postgres image:
```
Error: Database is uninitialized and superuser password is not specified.
        You must specify POSTGRES_PASSWORD for the superuser. Use
        "-e POSTGRES_PASSWORD=password" to set it in "docker run".

        You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
        without a password. This is *not* recommended. See PostgreSQL
        documentation about "trust":
        https://www.postgresql.org/docs/current/auth-trust.html
```
This error stops the Postgres container from launching, causing data-flow to error out
trying to connect to the db.

Adding the specified env var avoids this.